#!/bin/sh -

bspc monitor -d I II III IV V

bspc config normal_border_color     "#4C566A"
bspc config active_border_color     "#A3BE8C"
bspc config focused_border_color    "#88C0D0"
bspc config presel_feedback_color   "#BF616A"

bspc config border_width        3
bspc config window_gap          10
bspc config top_padding         34

bspc config split_ratio         0.5
bspc config gapless_monocle     false
bspc config click_to_focus      true

bspc desktop '^1' -l monocle

bspc rule -a 'Thunar' state=floating
bspc rule -a 'Xarchiver' state=floating

if [ -e "$PANEL_FIFO" ]
then
    bspc subscribe report > "$PANEL_FIFO" &
    pgrep -x panel > /dev/null
else
    panel &
fi
